FROM amazoncorretto:17-alpine-jdk
MAINTAINER KRO //quien es el dueño
COPY target/portfolioUno-0.0.1-SNAPSHOT.jar portafolio-app.jar   //copia el empaquetado a github 
ENTRYPOINT ["java","-jar","portafolio-app.jar"] //lo que se ejecuta primero
